# Generated by Django 4.1.7 on 2023-02-16 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('link', models.TextField(verbose_name='Ссылка на проект')),
                ('logo', models.ImageField(upload_to='', verbose_name='Лого проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('html_description', models.TextField(editable=False)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created'],
            },
        ),
    ]
