# Generated by Django 4.1.7 on 2023-02-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название проекта'),
        ),
    ]
