[tool.black]
line-length = 88
exclude = 'migrations/, venv/'
extend-exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true
skip = ['migrations', 'venv']